---
- hosts: aspproducers:rabbitmqconsumers
  become: yes
  become_method: sudo
  tasks:
  - name: Create directory
    file: 
      path: ~/rabbitMqChallenge
      state: directory
      
  - name: Check if packages-microsoft-prod.deb is installed
    command: dpkg-query -W packages-microsoft-prod
    register: packages_dotnet_checkdeb
    failed_when: packages_dotnet_checkdeb.rc > 1
    changed_when: packages_dotnet_checkdeb.rc == 1
  
  - name: Download Microsoft registration
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      dest: ~/rabbitMqChallenge
    when: packages_dotnet_checkdeb.rc == 1
      
  - name: Install my_package
    apt: deb="~/rabbitMqChallenge/packages-microsoft-prod.deb"
    when: packages_dotnet_checkdeb.rc == 1
      
  - name: Install the package "apt-transport-https"
    apt:
      name: apt-transport-https
      
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install the package "dotnet-sdk-2.1"
    apt:
      name: dotnet-sdk-2.1