---
- hosts: aspproducers:elkservers:rabbitmqconsumers:rabbitmqservers
  become: yes
  become_method: sudo
  tasks:   
  - name: "whoami?"
    shell: whoami
    register: whoami

  - debug: var=whoami.stdout
  
  - debug:
      msg: Hello World!
      
  - debug:
      msg: "User executing ansible: {{ lookup('env','HOME') }}"
      
  - command: "ls ~/"
    register: dir_out
    
  - debug: var={{item}}
    with_items: dir_out.stdout_lines